version: '3.7'

services:

  drupal:
    image: rnsrk/drupal_wisski:9.3.12
    restart: always
    build:
      context: ./drupal_context 
      dockerfile: Dockerfile
    volumes: 
       - drupal-data:/opt/drupal
       - ./drupal_context/settings.php:/opt/drupal/web/sites/default/settings.php
    ports:
      - "${DRUPAL_PORT}:80"

  mariadb:
    image: mariadb:10.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}      
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"

  solr:
    image: solr:8.11.1
    restart: always
    volumes:
      - solr-data:/opt/solr-8.11.1
    environment:
      SOLR_JAVA_MEM: "-Xms256M -Xmx512M"
    ports:
      - "${SOLR_PORT}:8983"

  graphdb:
    image: rnsrk/graphdb
    build: 
      context: ./graphdb_context
      dockerfile: Dockerfile
    volumes:
      - graphdb-data:/opt/graphdb
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.home=/opt/graphdb/home
        -Dgraphdb.hostname=graphdb
    volumes:
    ports:
      - "${GRAPHDB_PORT}:7200"

  phpmyadmin:
    image: phpmyadmin:5.1.3
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "${DRUPAL_PORT}:80"

volumes:
  drupal-data:
  graphdb-data:
  mariadb-data:
  solr-data:

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
