services:

  drupal:
    image: wisski/drupal_wisski:${DRUPAL_VERSION}
    restart: always
    depends_on:
      - graphdb
    build:
      context: ./drupal_context
      dockerfile: Dockerfile
      args:  # Pass environment variables to Dockerfile
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_DRIVER: ${DB_DRIVER}
        DB_PORT: ${DB_PORT}
    environment:
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DEFAULT_GRAPH: ${DEFAULT_GRAPH}
      DEFAULT_DATA_MODEL: ${DEFAULT_DATA_MODEL}
      DRUPAL_PASSWORD: ${DRUPAL_PASSWORD}
      DRUPAL_USER: ${DRUPAL_USER}
      DRUPAL_VERSION: ${DRUPAL_VERSION}
      SITE_NAME: ${SITE_NAME}

    volumes:
       - ./volumes/drupal-data:/opt/drupal
       - ./volumes/private_files:/var/www/private_files
    ports:
      - "${DRUPAL_PORT}:80"

  mariadb:
    image: mariadb:11.5
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USER}
      MARIADB_DATABASE: ${DB_NAME}
    volumes:
      - ./volumes/mariadb-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"

  solr:
    image: solr:9.7
    restart: always
    container_name: solr_wisski
    volumes:
      - solr-data:/var/solr
    environment:
      SOLR_JAVA_MEM: "-Xms256M -Xmx512M"
    ports:
      - "${SOLR_PORT}:8983"

  graphdb:
    image: wisski/graphdb
    restart: always
    build:
      context: ./graphdb_context
      dockerfile: Dockerfile
    volumes:
      - ./volumes/graphdb-data:/graphdb
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.home=/graphdb/home
        -Dgraphdb.hostname=graphdb
        -Xms512m
        -Xmx1024m
    ports:
      - "${GRAPHDB_PORT}:7200"

  adminer:
    image: adminer
    restart: always
    ports:
      - "${DB_ADMINISTRATION_PORT}:8080"
volumes:
  solr-data:

# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
