version: '3.7'

services:

  drupal:
    image: rnsrk/drupal_wisski:10.0.8
    restart: always
    build:
      context: ./drupal_context
      dockerfile: Dockerfile
    volumes:
       - ./volumes/drupal-data:/opt/drupal
       - ./volumes/private_files:/var/www/private_files
    ports:
      - "${DRUPAL_PORT}:80"

  mariadb:
    image: mariadb:10.10
    restart: always
    command: --transaction-isolation=READ-COMMITTED
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    volumes:
      - ./volumes/mariadb-data:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"

  solr:
    image: solr:8
    restart: always
    volumes:
      - solr-data:/var/solr
    environment:
      SOLR_JAVA_MEM: "-Xms256M -Xmx512M"
    ports:
      - "${SOLR_PORT}:8983"

  graphdb:
    image: rnsrk/graphdb
    restart: always
    build:
      context: ./graphdb_context
      dockerfile: Dockerfile
    volumes:
      - ./volumes/graphdb-data:/graphdb
    environment:
      GDB_JAVA_OPTS: >-
        -Dgraphdb.home=/graphdb/home
        -Dgraphdb.hostname=graphdb
    ports:
      - "${GRAPHDB_PORT}:7200"

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "${PHPMYADMIN_PORT}:80"
volumes:
  solr-data:
# vim: tabstop=2 softtabstop=0 expandtab shiftwidth=2 smarttab
